# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20180315_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
    ]
