# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_remove_question_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-date_updated']},
        ),
    ]
