# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_auto_20180317_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(unique=True),
        ),
    ]
