# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_auto_20180326_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
