# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0021_auto_20180403_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
