# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0024_comment_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='slug',
        ),
    ]
